home/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.basepage,name='basepage'),
    path('eventspage/',views.eventspage,name='eventspage'),
    path('teams/',views.teampage,name='teampage'),
    path('about/',views.aboutuspage,name='aboutuspage'),
    ]

llcd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lovcom/', include('lovcom.urls', namespace='lovcom')),
    path('', include('home.urls', namespace='home')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lovcom/urls.py
from django.urls import path

from . import views

app_name = 'lovcom'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('post_create', views.PostCreatView.as_view(), name='post_create'),

    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail,
        name='post_detail'),
]

home/models.py
from django.db import models

# Create your models here.

lovcom/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
        .filter(status='published')

class Post(models.Model):
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author =models.CharField(max_length=250)
    phone =models.CharField(max_length=250)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='published')

    def get_absolute_url(self):
        return reverse('lovcom:post_detail', args=[self.publish.year,
            self.publish.month, self.publish.day, self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

lovcom/forms.py
from .models import Comment, Post
from django import forms

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'author', 'body', 'phone' )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body',)

home/views.py
from django.shortcuts import render

def basepage(request):
    return render(request, 'index.html')

def eventspage(request):
    return render(request, 'eventspage.html')

def teampage(request):
    return render(request, 'teams.html')

def aboutuspage(request):
    return render(request, 'about.html')

lovcom/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, CreateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Post, Comment
from .forms import CommentForm, PostForm
# Create your views here.
class PostCreatView(CreateView):
    form_class = PostForm
    template_name = 'lovcom/post_create.html'

    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == 'SAVE':
            return super().form_valid(form)
        elif action == 'PREVIEW':
            preview = Post(
                body=form.cleaned_data['body'],
                title=form.cleaned_data['title'],
                author=form.cleaned_data['author'],
                phone=form.cleaned_data['phone'],
            )
            ctx = self.get_context_data(preview=preview)
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()

def post_list(request):
    posts = Post.published.all()
    return render(request, 'lovcom/post/list.html', {'posts': posts})

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'post'
    pagination_by = 30
    template_name = 'lovcom/post/list.html'

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year,
        publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'lovcom/post/detail.html', {'post': post, 'comments':comments,
                'new_comment': new_comment, 'comment_form': comment_form})

def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                'lovcom/post/list.html',
                {'page': page,
                'posts': posts})

home/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
     <link rel="stylesheet" href="{% static "css/style.css" %}">
     <link rel="stylesheet" href="{% static "css/events.css" %}">
     <link rel="stylesheet" href="{% static "css/form.css" %}">
     <link rel="stylesheet" href="{% static "css/blog_list.css" %}">
     <link rel="stylesheet" href="{% static "css/blog_detail.css" %}">
     <link rel="stylesheet" href="{% static "css/blog_admin_detail.css" %}">
     <link rel="stylesheet" href="{% static "css/about.css" %}">
     <link rel="stylesheet" href="{% static "css/team.css" %}">
     <link rel="stylesheet" href="{% static "css/contact.css" %}">
     <link rel="shortcut icon" href="{% static "css/img/churchlo.png" %}" type=image/x-icon>
</head>
<body>
    <script src={% static "js/header.js" %}></script>
    <header>
      <div class="top">
              <div class="top-logo">
                      <img src={% static "css/img/churchlo.png" %} alt="ChurchLogo">
                  </div>
                  <div class="top-name">
                          Love Leads Covenant Ministries <br> International Inc.
                  </div>

                  <div class="top-navigation">
                      <ul>
                          <li> <a href="{% url 'home:basepage' %}">HOME</a></li>
                          <li> <a href="{% url 'home:eventspage' %}">EVENTS</a></li>
                          <li> <a href="{% url 'home:teampage' %}">OUR TEAM</a></li>
                          <li> <a href="{% url 'home:aboutuspage' %}">ABOUT US</a></li>
                          <li> <a href="{% url 'lovcom:post_list' %}">LovCom</a></li>

                  </div>
      </div>
    </header>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    
  </div>
  <footer>
      <div class="main_footer">
          <div class="sub_footer">
              <div class="footer_logo">
                      <img src={% static "css/img/churchlo.png" %} alt="">
              </div>

              <div class="footer_name">
                      Love Lead Covenant Ministries International Inc.
              </div>
          </div>

          <div class="sub_footer_two">
              <div class="contact_title">
                  CONTACT US
                  <p>
                          # 1 Goshen Ave. Adeyemo bus-stop, Oluyole Industrial <br>
                           estate Ext. Ibadan, Oyo state, Nigeria.<br> <br>
                          KM 130, Plot 1&2 Olusegun Banjo Street, Lagos-Ibadan Express way, <br>
                          Academy Ibadan, Oyo State Nigeria. <br>
                          <br>
                          Tel:    07067726185, 09036509333
                  </p>
              </div>
          </div>
          <div class="sub_footer_three">
              <div class="quick_title">
                      QUICK LINKS
              </div>
              <ul>
                <li> <a href="{% url 'home:basepage' %}">HOME</a></li>
                <li> <a href="{% url 'home:eventspage' %}">EVENTS</a></li>
                <li> <a href="{% url 'home:teampage' %}">OUR TEAM</a></li>
                <li> <a href="{% url 'home:aboutuspage' %}">ABOUT US</a></li>
                <li> <a href="{% url 'lovcom:post_list' %}">LovCom</a></li>

              </ul>
          </div>
      </div>

      <div class="red_footer">
          <div class="copyright">
              &copy; 2020  <span>Love Leads Covenant Ministries  International Inc.</span>
          </div>

          <div class="copyright" id="right">
              &copy; 2020  <span>LLCM.</span>
          </div>

          <div class="follow">
              <div class="follow_text">
                  FOLLOW US ON:
              </div>
              <div class="follow_logo">
                      <a href="www.facebook.com/Loveleads">
                      <img src="{% static "css/img/icon/icons8-facebook-480.png" %}" alt="">

                      </a>
              </div>

              <div class="follow_logo">
                      <a href="www.instagram.com/loveleadscm">
                              <img src="{% static "css/img/icon/icons8-instagram-480.png" %}" alt="">

                              </a>
             </div>

              <div class="follow_logo">
                      <a href="www.twitter.com/Loveleads4">
                              <img src="{% static "css/img/icon/icons8-twitter-480.png" %}" alt="">

                              </a>

              </div>

      </div>
      </div>
  </footer>
</body>

</html>
</html>

home/templates/eventspage.html
{% extends 'index.html' %}
{% load static %}
{% block title %} About Us | LLCM{% endblock %}
{% block content %}

                <div class="events_container">
                    <div class="events_big_title">
                        Our Events
                    </div>

                    <div class="events_details_div">
                            <div class="events_details_time">
                                        <div class="date_events">
                                                SUNDAY SERVICE
                                        </div>
                                        <div class="month_events">
                                            Every Sunday
                                    </div>


                            </div>


                            <div class="events_details_picture">
                                    <img src= "{% static 'css/img/johnmark.jpg' %}" alt="">

                            </div>


                            <div class="events_details_details">
                                    <div class="events_details_details_title">
                                            Sunday Service
                                    </div>

                                    <div class="events_details_details_location">
                                        Love Feast Hour Time <br>
                                9:00am - 11:00am <br>
                                        ADDRESS: <br><br>
                                1 Goshen Ave. Adeyemo bus-stop, Oluyole Industrial
                                estate Ext. Ibadan, Oyo state, Nigeria.
                                    </div>

                                    <!-- <div class="events_details_details_realdetails">
                                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos quas nulla consequuntur
                                             magni. Repellendus quam nostrum consequuntur saepe illum.
                                             Corporis beatae, eligendi modi veritatis tenetur autem accusamus harum velit quia.
                                    </div> -->

                            </div>
                    </div>



                    <div class="events_details_div">
                        <div class="events_details_time">
                                    <div class="date_events">
                                            MID-WEEK SERVICE
                                    </div>
                                    <div class="month_events">
                                        Every Wednesday
                                </div>


                        </div>


                        <div class="events_details_picture">
                                <img src="{% static 'css/img/bible study (2).jpg' %}" alt="">
                        </div>


                        <div class="events_details_details">
                                <div class="events_details_details_title">
                                    MID-WEEK SERVICE
                                </div>

                                <div class="events_details_details_location">
                                    BreakThroughs Hour <br>
                                5:00PM - 7:00PM <br>
                                ADDRESS: <br><br>
                                1 Goshen Ave. Adeyemo bus-stop, Oluyole Industrial
                                estate Ext. Ibadan, Oyo state, Nigeria.

                                </div>

                                <!-- <div class="events_details_details_realdetails">
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos quas nulla consequuntur
                                         magni. Repellendus quam nostrum consequuntur saepe illum.
                                         Corporis beatae, eligendi modi veritatis tenetur autem accusamus harum velit quia.
                                </div> -->

                        </div>
                    </div>
                </div>

                {% endblock %}

home/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} About Us | LLCM{% endblock %}
{% block content %}

        <div class="container">
                <div class="outer">
                    <div class="details">
                            You are welcome to Love Lead Covenant Ministries International Inc.
                    <br>
                        <span>
                            ...Preaching, teaching, and showing the Love that saved the world
                        </span>
                    </div>
                </div>
        </div>

        <div class="quote">
            <div class="pastor">
                    <img src={% static "css/img/sap.jpg" %} alt="">

            </div>
            <div class="pastor_name">
                PASTOR JOHNSON A. PATRICK (Baba Africa)
            </div>

            <div class="pastor_quote">
                    <i>
                        Brethren, there is no small vision or ministry in life, <br>
                        neither is there any muster seed without a potential to become a great tree <br>
                        but it is clearly the man inputs that determines his/her outputs. <br>
                    </i>
                </div>
        </div>

        <div class="events_div">
            <div class="events_title">
                UPCOMING EVENTS
            </div>

            <div class="events_box">
                 <div class="events_pics">
                    <img src={% static "css/img/pexels-luis-quintero-2351722.jpg" %} alt="">

                 </div>
                 <div class="events_details">
                    <div class="events_name">
                        SUNDAY SERVICE (Love Feast Hour Time)
                    </div>
                     <div class="events_info">
                            This book of the law shall not depart from your mouth for you shall
                            meditate in it day and night, then he shall make your ways properous
                            and you shall find good success - <span>Joshua 1:8 (NLT)</span> <br>
                            Just us every Sunday by 9:00am as we worship Jesus the Love of God
                        </div>

                        <a href="{% url 'home:eventspage' %}" class="a_more">
                            <div class="events_more">
                                READ MORE
                             </div>
                           </a>


                    </div>

            </div>


            <div class="events_box">
                    <div class="events_pics">
                       <img src={% static "css/img/pexels-luis-quintero-2351719.jpg" %} alt="">

                    </div>
                    <div class="events_details">
                       <div class="events_name">
                        MID-WEEK SERVICE (BreakThroughs Hour)
                       </div>
                        <div class="events_info">
                            He who opens the breach goes up before them; they break through and
                            pass the gate, going out by it. Their king passes on before them, the Lord
                            at their head - <span>Micah 2:13</span> <br>
                            Just us every Wednesday by 5:00PM
                           </div>

                           <a href="{% url 'home:eventspage' %}" class="a_more">
                            <div class="events_more">
                                READ MORE
                             </div>
                           </a>

                       </div>

               </div>
        </div>

        {% endblock %}

lovcom/templates/lovcom/post/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<div class="container_question">

              <div class="comment_show">
                  <div class="comment_box">
                      <div class="long_comment_pics">
                          <div class="profile_avatar">
                                 <img src="{% static "css/img/icon/user.png" %}">
                          </div>
                          <div class="commenter_name">
                              {{ post.author }}
                          </div>
                      </div>
                      <div class="comment_date">
                           {{ post.publish }}
                      </div>
                      <div class="comment_text">
                              <h1>{{ post.title }}</h1>
                              {{ post.body|linebreaks }}
                      </div>
                  </div>

              </div>

  <div class="">
                  <div class="reply_box">
                    {% with comments.count as total.comments %}
                      <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
                    {% endwith %}
                    {% for comment in comments %}
                      <div class="long_comment_pics">
                          <div class="profile_avatar">
                                 <img src="{% static "css/img/icon/user.png" %}">
                          </div>
                          <div class="commenter_name">
                              {{ comment.name }}
                          </div>
                      </div>
                      <div class="comment_date">
                          {{ comment.created }} - Replied post
                      </div>
                      <div class="comment_text">
                        {{ comment.body|linebreaks }}
                        Comment {{ forloop.counter }}
                      </div>
                    {% empty %}
                      <p>There are no comments yet.</p>
                    {% endfor %}
                </div>
    </div>

  {% if new_comment %}
    <h2>Your comment has been added.</h2>
  {% else %}
  <p> </p>
  <p> .</p>
  <div class="events_title">
    <p><h2>Respond to question</h2></p>
  </div>

    <div class="form_question">
      <div class="contact-us">
        <form action="." method="post">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button id="customerOrder">SUBMIT</button>
          <!-- <p><input id="customerOrder" type="submit" value="Add comment"></p> -->
        </form>
  {% endif %}
  </div>
  </div>
{% endblock %}

lovcom/templates/lovcom/post/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}LoveCom{% endblock %}
{% block content %}
  <div class="main_blog_div">
    <div class="reply_box" >
    <h2>Love Community</h2>
      <p>This is a community of love. You can post your questions and suggestions
       and you'd get a response as soon as possible.</p>
    <div class="form_link">

      <a href="{% url 'lovcom:post_create' %}">Click Here To Post A Question</a>
    </div>

    </div>

    {% for post in posts %}
    <div class="comment_box">
           <div class="long_comment_pics">
               <div class="profile_avatar">
                 <img src="{% static 'css/img/icon/user.png' %}"  alt="">
               </div>

           </div>
           <div class="commenter_name">
               <a href="{{ post.get_absolute_url }}"> {{ post.author }} </a>
           </div>
           <div class="comment_date">
                {{ post.publish }}
           </div>

           <div class="blog_list_name">
               <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a>
           </div>

           <div class="reply">
             {{ post.body|truncatewords:40|linebreaks }}
               <a href="{{ post.get_absolute_url }}"> Read more... </a>
           </div>
       </div>
  </div>
  {% empty %}
    <p>No questions yet'</p>


  {% endfor %}

  {% include "pagination.html" with page=page_obj %}
{% endblock %}

lovcom/templates/lovcom/post_create.html
{% extends "base.html" %}

{% block title %}Ask a question{% endblock %}
{% block content %}
  <div class="events_title">
    <h1>Ask a question or Make a suggestion</h1>
    <h5>
      Please ask your question or suggestion We will be happy to respond.
    </h5>
    {% if preview %}
      <div class="">
        Question Preview
        <div class="">
          <h1>{{ preview.title }}</h1>
          {{ preview.body }}
        </div>

      </div>
    {% endif %}
    <div class="form_question">
        <div class="contact-us">
          <form class="" action="" method="post">  {% csrf_token %}
            {{ form }}
            <button type="submit" name="action" value='PREVIEW'>Preview</button>
            <button type="submit" name="action" value='SAVE' >Ask! </button>
          </form>
        </div>
        </div>

  </div>
{% endblock %}

lovcom/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
  </span>
</div>